#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define SCREEN_X 320
#define SCREEN_Y 240
#define LINES 40
#define COLUMNS 20
#define BLOCK_SIZE 5
#define MAX_ROTATIONS 4
#define INITIAL_LIMIT_X 112
#define FINAL_LIMIT_X 212
#define INITIAL_LIMIT_Y 18

#define COLOR_WHITE 0xFFFF
#define COLOR_YELLOW 0xFFE0
#define COLOR_RED 0xF800
#define COLOR_GREEN 0x07E0
#define COLOR_BLUE 0x041F
#define COLOR_CYAN 0x07FF
#define COLOR_MAGENTA 0xF81F
#define COLOR_GREY 0xC618
#define COLOR_PINK 0xFC18
#define COLOR_ORANGE 0xFC00

typedef enum
{
    TETROMINO_Q = 0,
    TETROMINO_L = 1,
    TETROMINO_I = 2,
} TetrominoTipo;

#endif
